[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-interaction --prefer-dist --no-dev"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
